# should be updated? https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ networking.k8s.io/v1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sodevsalary-ingress
  labels:
    app.kubernetes.io/component: controller
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  #controller: k8s.io/ingress-nginx
  ingressClassName: nginx
  rules:
    - host: demo.sodevsalary.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: application-http-frontend
                port:
                  number: 80
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: application-http-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: application-http-api
                port:
                  number: 8121