server:
  port: 8082

spring:
  batch:
    jdbc:
      #schema: classpath:org/springframework/batch/core/schema-postgres.sql
      schema: classpath:org/springframework/batch/core/schema-h2.sql

      initialize-schema: always
    job:
      enabled: true
    #spring:
    #  batch:
    #    initializer:
    #      enabled: true
    #    jdbc:
    # https://stackoverflow.com/a/65473668/8524651
  # initialize-schema: never # always
  #config:
  #  import: classpath:/application-prod.properties

