# TODO: activate logs and optimize bulk inserts
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        show_sql: false

  batch:
    jdbc:
      # https://stackoverflow.com/a/75480766/8524651
      # init custom spring batch tables. Seems to initialize our tablesas well.
      initialize-schema: always

