test: 99999
spring:
  config:
    imports: classpath:/application-prod-persistence.properties

  # https://www.cockroachlabs.com/blog/tutorial-spring-hibernate/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9999/postgres
    username: sodevuser
    password: sodevuserpw
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

# 2024-06-18T16:22:31.904+02:00  INFO 15596 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
  devtools:
    add-properties: false

# 2024-06-18T16:22:31.905+02:00  INFO 15596 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
logging:
  level:
    web: DEBUG